/* generated by pipeline/publish.py from queue/posts.json - do not edit */
window.PREVIEW_DATA = {"campaigns": [], "linkChecks": [], "linkCheckedAt": "", "tokens": {}, "people": {}, "socialDefault": {"reactors": "", "comments": 0, "reposts": 0}};
window.STUDIO = {
 "profiles": [
  {
   "id": "company",
   "name": "BigHammer.ai",
   "kind": "company",
   "headline": "AI data engineering platform",
   "tz": "UK",
   "avatar": "media/avatars/company.png",
   "avatar_ok": true
  },
  {
   "id": "srinath",
   "name": "Srinath Reddy",
   "kind": "person",
   "headline": "Founder & CEO at BigHammer.ai | Data platforms, cost and AI",
   "tz": "UK",
   "avatar": "media/avatars/srinath.jpg",
   "avatar_ok": true
  },
  {
   "id": "richard",
   "name": "Richard Lawrence",
   "kind": "person",
   "headline": "BigHammer.ai | Data integration and enterprise data platforms",
   "tz": "UK",
   "avatar": "media/avatars/richard.jpg",
   "avatar_ok": false
  },
  {
   "id": "terry",
   "name": "Terry",
   "kind": "person",
   "headline": "BigHammer.ai",
   "tz": "ET",
   "avatar": "media/avatars/terry.jpg",
   "avatar_ok": false
  }
 ],
 "posts": [
  {
   "id": "C1",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-06",
   "time": "10:00",
   "idea": "W3: the 7 system tables that explain a Databricks bill",
   "format": "Single image · dense cheat-sheet infographic",
   "sample": {
    "id": "AV44",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "8-panel dark cheat sheet: numbered category panels, stat tiles, real table, red-flag list, numbered checklist",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7458455008015974400"
   },
   "copy_basis": "Sample AV44's own copy structure (stat-led hook, numbered sections, arrow lists, closing question). Beats the prompt-doc Thought Leadership template for a reference infographic.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "C1",
    "tall": false,
    "files": [
     "media/C1/image.jpg"
    ]
   },
   "text": "Your Databricks bill already explains itself.\n\nThe explanation sits in 7 read-only tables most teams never query.\n\nHere's what each one tells you:\n\n1. Billing\n\n→ billing.usage: what you spent, on which SKU, for which job\n→ billing.list_prices: what each unit cost at the time\n\n2. Jobs\n\n→ lakeflow.jobs: which jobs exist and who owns them\n→ job_run_timeline: which runs failed or timed out\n→ job_task_run_timeline: which task inside a job burned the time\n\n3. Compute\n\n→ compute.clusters: how each cluster was sized, tagged and set to shut down\n→ compute.node_timeline: how busy the nodes were, minute by minute\n\nTwo things catch teams out.\n\nJobs that run on All-Purpose clusters carry no job ID in billing. That spend can't be traced to a job at all.\n\nAnd CPU history is only kept for 90 days, while billing and job history last 365. Your utilisation evidence expires first.\n\nStart with five numbers this week:\n\n→ 90-day cost by product\n→ Share of spend with a job ID\n→ What failed runs cost\n→ Top 10 jobs, each with an owner\n→ Clusters averaging under 20% CPU\n\nOn 15 October, Srinath Reddy runs these on a real bill, live.\n\nWhich of the 7 does your team already query?\n\n#Databricks #FinOps #DataEngineering",
   "first_comment": "If a Databricks bill lands on your desk, block out 45 minutes for this. Srinath walks through all 7 tables, the 5 numbers to pull first, and how to turn them into a renewal plan you can defend. Live on Thu 15 Oct, 12:00 PM ET: https://webinar.bighammerai.com/",
   "sources": [
    "Databricks system tables docs (retention, 12 h billing lag, admin access)",
    "Databricks billing docs: job_id not populated for all-purpose compute",
    "BigHammer email series Issues 1, 2, 4, 6"
   ],
   "numbers_for_signoff": [
    "365 / 90 day retention",
    "~12 hour billing lag",
    "20% CPU threshold"
   ],
   "short": "7 tables behind your bill"
  },
  {
   "id": "C2",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-12",
   "time": "10:00",
   "idea": "W7: Which jobs belong on Databricks (5 outcomes, not 1)",
   "format": "Single image · true 2x2 decision matrix",
   "sample": {
    "id": "AV35",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "2x2 tier-list matrix with axis labels, 2-3 rated cards per quadrant, tag pills, legend",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7463164988585635840"
   },
   "copy_basis": "Sample AV35's tier-list copy (numbered quadrant sections with a one-line verdict each), adapted to 5 outcomes.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "C2",
    "tall": false,
    "files": [
     "media/C2/image.jpg"
    ]
   },
   "text": "\"Should we move off Databricks?\" is the wrong question.\n\nIt forces an all or nothing answer. Neither answer is right.\n\nThe better question is: which jobs?\n\nScore every job on two things. How complex it is, and how much it depends on Databricks-only features.\n\nYou get five answers instead of one:\n\n1. Keep on Databricks\nHigh complexity, high dependency. ML training and scoring, declarative pipelines, Feature Store. This is where the platform earns its price.\n\n2. Optimize, then evaluate\nComplex, but plain Spark underneath. Tune it first. Decide later.\n\n3. Migrate\nSimple and low dependency. Nightly batch ETL, source to target loads, Scala JAR and PySpark wheel jobs. Real candidates for public cloud Spark.\n\n4. Evaluate\nSomewhere in between. Small jobs on dbutils, code tied to three-part table names. Get more data before you decide.\n\n5. Defer\nToo small in cost to be worth moving yet.\n\nWhat counts as a dependency signal:\n\n→ dbutils calls\n→ Unity Catalog three-part names\n→ the dlt module\n→ Databricks Connect\n\nDecisions made job by job. Never platform wide.\n\nOn 15 October we walk through this sort live, with the scores and the reasons behind each call.\n\nWhich quadrant holds most of your spend?\n\n#Databricks #DataEngineering #DataPlatform",
   "first_comment": "Curious where your own top 20 jobs would land? Srinath runs the complexity and dependency scoring live on Thu 15 Oct, 12:00 PM ET, then takes your questions. Save a seat here: https://webinar.bighammerai.com/",
   "sources": [
    "BigHammer email series Issue 7 (5-outcome classification)",
    "Databricks docs: dbutils, Databricks Connect, declarative pipelines"
   ],
   "numbers_for_signoff": [],
   "short": "Which jobs belong on Databricks"
  },
  {
   "id": "C3",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-15",
   "time": "10:00",
   "idea": "W12: day-of masterclass reminder",
   "format": "Single image · webinar promo poster with speaker cutout",
   "sample": {
    "id": "AV08",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Webinar poster: date line, LIVE chip, big headline, cutout speaker(s) at base, name pills",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7477298534065680384"
   },
   "copy_basis": "Sample AV08's event-promotion narrative (what happens, two layers of detail, time, link below).",
   "cta": true,
   "media": {
    "type": "image",
    "src": "C3",
    "tall": false,
    "files": [
     "media/C3/image.jpg"
    ]
   },
   "text": "Today at 12:00 PM ET, Srinath Reddy goes live.\n\n45 minutes on where Databricks spend actually goes, and the framework enterprise data teams use to reduce it by up to 75%.\n\nMinutes 0 to 30: the framework\n\n→ Assess: turn 90 days of billing and run data into a baseline you can defend\n→ Migrate: move the right jobs, in waves, and prove parity before cutover\n→ Monitor: catch drift before it lands on next quarter's bill\n\nMinutes 30 to 45: your questions\n\n→ Bring the hardest cost question you have\n→ The best three questions win a $50 Amazon gift card\n\n5 PM UK · 6 PM CET · 9 AM PT · 9:30 PM IST\n\nThe link to join is in the first comment.\n\n#Databricks #FinOps #Webinar",
   "first_comment": "Starting at 12:00 PM ET today. If a Databricks renewal is on your desk this quarter, bring your team and bring your hardest question: https://webinar.bighammerai.com/",
   "sources": [
    "facts.md: owner-confirmed date/time",
    "webinar page: structure, gift cards, 'up to 75%' title"
   ],
   "numbers_for_signoff": [
    "up to 75%",
    "$50 gift card, top 3 questions"
   ],
   "short": "Day-of masterclass poster"
  },
  {
   "id": "C4",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-20",
   "time": "10:00",
   "idea": "N6: legacy ETL tools that changed owner or status",
   "format": "Single image · status cards with timelines",
   "sample": {
    "id": "AV28",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "7 strategy cards, each with a colored numbered band, mini diagram and RETIRE -> RUN -> PROOF strip, plus a repost card",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7467150856392560640"
   },
   "copy_basis": "Sample AV28's numbered 'plays' copy (context stats, then 1/ to n/ with a line each, then a send-it-to line).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "C4",
    "tall": false,
    "files": [
     "media/C4/image.jpg"
    ]
   },
   "text": "Four legacy data tools changed hands in the last three years.\n\nIf one of them runs your pipelines, your 2027 plan needs a line for it.\n\n1. Informatica PowerCenter\nSalesforce completed its acquisition of Informatica in November 2025. Standard support for PowerCenter 10.5 is reported to have ended in March 2026, with paid extended support after that.\n\n2. Talend Open Studio\nQlik retired the free edition on 31 January 2024. It is no longer hosted or updated.\n\n3. StreamSets\nIBM completed its acquisition in July 2024. It now sits inside IBM's wider data integration suite.\n\n4. Cloudera CDH and HDP\nBoth are past end of support. On-prem Cloudera 7.3.1 reaches end of support in December 2026.\n\nNone of this makes these tools bad. Plenty of pipelines run on them today, and run well.\n\nBut a new owner or a closing support window changes the renewal conversation. You have three options:\n\n→ Stay and pay for extended support. It buys time, not a plan.\n→ Move to the vendor's cloud. Same vendor, new platform, new contract.\n→ Own the logic. Convert the pipelines to open code that lives in your own repo.\n\nWhich one is your team planning for?\n\nSources: Salesforce, Qlik, IBM, Cloudera support lifecycle. PowerCenter dates per Informatica's lifecycle guide.\n\n#DataEngineering #ETL #DataLeadership",
   "first_comment": "",
   "sources": [
    "Salesforce press release 18 Nov 2025",
    "Qlik Talend Open Studio page",
    "IBM newsroom 1 Jul 2024",
    "Cloudera support lifecycle page",
    "PowerCenter 10.5 date: LIKELY, confirm with Informatica lifecycle guide before publishing"
   ],
   "numbers_for_signoff": [
    "All dates"
   ],
   "short": "Legacy ETL tools changed hands"
  },
  {
   "id": "C5",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-27",
   "time": "10:00",
   "idea": "N8: three kinds of people do data engineering",
   "format": "Single image · 3-circle Venn with intersections",
   "sample": {
    "id": "AV40",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Proportional 3-circle Venn, labelled pairwise intersections, center thesis, numbered rule cards",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7460627938871418880"
   },
   "copy_basis": "Sample AV40's copy (what each circle does, what breaks where two overlap, the rules we run by).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "C5",
    "tall": false,
    "files": [
     "media/C5/image.jpg"
    ]
   },
   "text": "Three kinds of people do data engineering. Only one of them has it in their job title.\n\nThe data engineer\nCarries a backlog from every team. Owns what reaches production. Wants the design work back.\n\nThe analyst who never signed up for it\nHas to join sources and work out why two numbers disagree before the real analysis can start.\n\nThe product team whose app runs on data\nNeeds data plumbing under the product. Builds it once, then maintains it forever.\n\nWhere they overlap is where the pain lives:\n\n→ Two sources disagree, and reconciliation belongs to nobody\n→ A field means one thing in the report and another in the app\n→ The app depends on pipelines its own team never designed\n\nWe built BigHammer.ai for all three, on one shared foundation:\n\n1. Meaning stays attached. A field means the same thing in the pipeline, the report and the app.\n2. AI where it helps. Fixed, predictable rules wherever the workflow needs them.\n3. Logic in your repo. The business knowledge you build stays in your own GitHub.\n\nWhich of the three are you, most weeks?\n\n#DataEngineering #Analytics #AI",
   "first_comment": "",
   "sources": [
    "Richard Lawrence, 'general overview' doc: three audiences, context engine, deterministic rules, customer GitHub"
   ],
   "numbers_for_signoff": [],
   "short": "3 kinds of people do DE"
  },
  {
   "id": "C6",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-02",
   "time": "10:00",
   "idea": "N9: Databricks Budgets are GA; tags decide if they work",
   "format": "Single image · vertical flowchart branching into tiers",
   "sample": {
    "id": "AV26",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Single-column pipeline of step cards with tool chips, branching into 3 tier cards, final sync box, dashed feedback loop",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7467876018767196160"
   },
   "copy_basis": "Sample AV26's step-by-step system copy (Step 1 to 6 with the why under each, closing line, question).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "C6",
    "tall": false,
    "files": [
     "media/C6/image.jpg"
    ]
   },
   "text": "Databricks Budgets went GA in July.\n\nMost teams will set one budget for the whole account. It will tell them almost nothing.\n\nA budget is only as useful as the tags underneath it. Here's the order that works:\n\n1. Pick three tags. No more.\nowner, cost_center, environment.\n\n2. Enforce them with a cluster policy.\nA policy can require a cost centre tag before compute will launch. No tag, no cluster.\n\n3. Fix the spend that can't carry a tag.\nScheduled work on All-Purpose clusters moves to job compute, so every run is traceable.\n\n4. Check tag coverage in system.billing.usage.\nWhat share of spend actually carries the tags? That's your real starting line.\n\n5. Now create budgets, per tag.\nOne per team. One per environment, because non-prod is where drift hides. A monthly showback by owner for the top 10 jobs.\n\nThen review spend against the value it delivered, every month.\n\nAnd report untagged spend as a visibility gap. Never as savings.\n\nWhat share of your spend carries an owner tag today?\n\n#Databricks #FinOps #CloudCost",
   "first_comment": "",
   "sources": [
    "Databricks release notes Jul 2026: Budgets GA",
    "Databricks cluster policy docs: required COST_CENTER tag example",
    "BigHammer email series Issue 2"
   ],
   "numbers_for_signoff": [],
   "short": "Budgets need tags"
  }
 ],
 "webinar_url": "https://webinar.bighammerai.com/"
};
