/* generated by pipeline/publish.py from queue/posts.json - do not edit */
window.PREVIEW_DATA = {"campaigns": [], "linkChecks": [], "linkCheckedAt": "", "tokens": {}, "people": {}, "socialDefault": {"reactors": "", "comments": 0, "reposts": 0}};
window.STUDIO = {
 "profiles": [
  {
   "id": "company",
   "name": "BigHammer.ai",
   "kind": "company",
   "headline": "AI data engineering platform",
   "tz": "UK",
   "avatar": "media/avatars/company.png",
   "avatar_ok": true
  },
  {
   "id": "srinath",
   "name": "Srinath Reddy",
   "kind": "person",
   "headline": "Founder & CEO at BigHammer.ai | Data platforms, cost and AI",
   "tz": "ET",
   "avatar": "media/avatars/srinath.jpg",
   "avatar_ok": true
  },
  {
   "id": "richard",
   "name": "Richard Lawrence",
   "kind": "person",
   "headline": "BigHammer.ai",
   "tz": "UK",
   "avatar": "media/avatars/richard.jpg",
   "avatar_ok": true
  },
  {
   "id": "terry",
   "name": "Terry Dhariwal",
   "kind": "person",
   "headline": "BigHammer.ai",
   "tz": "UK",
   "avatar": "media/avatars/terry.jpg",
   "avatar_ok": true
  }
 ],
 "posts": [
  {
   "id": "C1",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-05",
   "time": "10:00",
   "idea": "W3: the 7 system tables that explain a Databricks bill",
   "format": "Single image · dense cheat-sheet infographic",
   "sample": {
    "id": "AV44",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "8-panel dark cheat sheet: numbered category panels, stat tiles, real table, red-flag list, numbered checklist",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7458455008015974400"
   },
   "copy_basis": "Sample AV44's own copy structure (stat-led hook, numbered sections, arrow lists, closing question). Beats the prompt-doc Thought Leadership template for a reference infographic.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "C1",
    "tall": false,
    "files": [
     "media/C1/image.jpg?v=202610010132"
    ]
   },
   "text": "Your Databricks bill already explains itself.\n\nThe explanation sits in 7 read-only tables most teams never query.\n\nHere's what each one tells you:\n\n1. Billing\n\n→ billing.usage: what you spent, on which SKU, for which job\n→ billing.list_prices: what each unit cost at the time\n\n2. Jobs\n\n→ lakeflow.jobs: which jobs exist and who owns them\n→ job_run_timeline: which runs failed or timed out\n→ job_task_run_timeline: which task inside a job burned the time\n\n3. Compute\n\n→ compute.clusters: how each cluster was sized, tagged and set to shut down\n→ compute.node_timeline: how busy the nodes were, minute by minute\n\nTwo things catch teams out.\n\nJobs that run on All-Purpose clusters carry no job ID in billing. That spend can't be traced to a job at all.\n\nAnd CPU history is only kept for 90 days, while billing and job history last 365. Your utilisation evidence expires first.\n\nStart with five numbers this week:\n\n→ 90-day cost by product\n→ Share of spend with a job ID\n→ What failed runs cost\n→ Top 10 jobs, each with an owner\n→ Clusters averaging under 20% CPU\n\nOn Thursday 15 October, our founder and CEO Srinath Reddy runs these on a real bill in a free live masterclass.\n\nWhich of the 7 does your team already query?\n\n#Databricks #FinOps #DataEngineering",
   "first_comment": "If a Databricks bill lands on your desk, block out 45 minutes on Thu 15 Oct at 12:00 PM ET. In our free live masterclass, BigHammer.ai founder and CEO Srinath Reddy walks through all 7 tables, the 5 numbers to pull first, and how to turn them into a renewal plan you can defend. Save a seat: https://webinar.bighammerai.com/",
   "sources": [
    "Databricks system tables docs (retention, 12 h billing lag, admin access)",
    "Databricks billing docs: job_id not populated for all-purpose compute",
    "BigHammer email series Issues 1, 2, 4, 6"
   ],
   "numbers_for_signoff": [
    "365 / 90 day retention",
    "~12 hour billing lag",
    "20% CPU threshold"
   ],
   "short": "7 tables behind your bill"
  },
  {
   "id": "C2",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-06",
   "time": "10:00",
   "idea": "W7: Which jobs belong on Databricks (5 outcomes, not 1)",
   "format": "Single image · true 2x2 decision matrix",
   "sample": {
    "id": "AV35",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "2x2 tier-list matrix with axis labels, 2-3 rated cards per quadrant, tag pills, legend",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7463164988585635840"
   },
   "copy_basis": "Sample AV35's tier-list copy (numbered quadrant sections with a one-line verdict each), adapted to 5 outcomes.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "C2",
    "tall": false,
    "files": [
     "media/C2/image.jpg?v=202610010132"
    ]
   },
   "text": "\"Should we move off Databricks?\" is the wrong question.\n\nIt forces an all or nothing answer. Neither answer is right.\n\nThe better question is: which jobs?\n\nScore every job on two things. How complex it is, and how much it depends on Databricks-only features.\n\nYou get five answers instead of one:\n\n1. Keep on Databricks\nHigh complexity, high dependency. ML training and scoring, declarative pipelines, Feature Store. This is where the platform earns its price.\n\n2. Optimize, then evaluate\nComplex, but plain Spark underneath. Tune it first. Decide later.\n\n3. Migrate\nSimple and low dependency. Nightly batch ETL, source to target loads, Scala JAR and PySpark wheel jobs. Real candidates for public cloud Spark.\n\n4. Evaluate\nSomewhere in between. Small jobs on dbutils, code tied to three-part table names. Get more data before you decide.\n\n5. Defer\nToo small in cost to be worth moving yet.\n\nWhat counts as a dependency signal:\n\n→ dbutils calls\n→ Unity Catalog three-part names\n→ the dlt module\n→ Databricks Connect\n\nDecisions made job by job. Never platform wide.\n\nOn Thursday 15 October, our founder and CEO Srinath Reddy walks through this sort live, with the scores and the reasons behind each call.\n\nWhich quadrant holds most of your spend?\n\n#Databricks #DataEngineering #DataPlatform",
   "first_comment": "Curious where your own top 20 jobs would land? In our free live masterclass on Thu 15 Oct at 12:00 PM ET, BigHammer.ai founder and CEO Srinath Reddy runs the complexity and dependency scoring on real examples, then answers your questions. Save a seat: https://webinar.bighammerai.com/",
   "sources": [
    "BigHammer email series Issue 7 (5-outcome classification)",
    "Databricks docs: dbutils, Databricks Connect, declarative pipelines"
   ],
   "numbers_for_signoff": [],
   "short": "Which jobs belong on Databricks"
  },
  {
   "id": "C3",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-07",
   "time": "10:00",
   "idea": "W12: masterclass announcement poster (Thu 15 Oct)",
   "format": "Single image · webinar promo poster with speaker cutout",
   "sample": {
    "id": "AV08",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Webinar poster: date line, LIVE chip, big headline, cutout speaker(s) at base, name pills",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7477298534065680384"
   },
   "copy_basis": "Sample AV08's event-promotion narrative (what happens, two layers of detail, time, link below).",
   "cta": true,
   "media": {
    "type": "image",
    "src": "C3",
    "tall": false,
    "files": [
     "media/C3/image.jpg?v=202610010132"
    ]
   },
   "text": "Next Thursday, 15 October, at 12:00 PM ET, our founder and CEO Srinath Reddy goes live.\n\n45 minutes on where Databricks spend actually goes, and the framework enterprise data teams use to reduce it by up to 75%.\n\nMinutes 0 to 30: the framework\n\n→ Assess: turn 90 days of billing and run data into a baseline you can defend\n→ Migrate: move the right jobs, in waves, and prove parity before cutover\n→ Monitor: catch drift before it lands on next quarter's bill\n\nMinutes 30 to 45: your questions\n\n→ Bring the hardest cost question you have\n→ The best three questions win a $50 Amazon gift card\n\n5 PM UK · 6 PM CET · 9 AM PT · 9:30 PM IST\n\nIt is free. The link to save your seat is in the first comment.\n\n#Databricks #FinOps #Webinar",
   "first_comment": "Free, 45 minutes, Thursday 15 October at 12:00 PM ET. If a Databricks renewal is on your desk this quarter, bring your team and your hardest question. Save your seat: https://webinar.bighammerai.com/",
   "sources": [
    "facts.md: owner-confirmed date/time",
    "webinar page: structure, gift cards, 'up to 75%' title"
   ],
   "numbers_for_signoff": [
    "up to 75%",
    "$50 gift card, top 3 questions"
   ],
   "short": "Masterclass poster"
  },
  {
   "id": "C4",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-03",
   "time": "10:00",
   "idea": "N6: legacy ETL tools that changed owner or status",
   "format": "Single image · status cards with timelines",
   "sample": {
    "id": "AV28",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "7 strategy cards, each with a colored numbered band, mini diagram and RETIRE -> RUN -> PROOF strip, plus a repost card",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7467150856392560640"
   },
   "copy_basis": "Sample AV28's numbered 'plays' copy (context stats, then 1/ to n/ with a line each, then a send-it-to line).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "C4",
    "tall": false,
    "files": [
     "media/C4/image.jpg?v=202610010132"
    ]
   },
   "text": "Four legacy data tools changed hands in the last three years.\n\nIf one of them runs your pipelines, your 2027 plan needs a line for it.\n\n1. Informatica PowerCenter\nSalesforce completed its acquisition of Informatica in November 2025. Standard support for PowerCenter 10.5 is reported to have ended in March 2026, with paid extended support after that.\n\n2. Talend Open Studio\nQlik retired the free edition on 31 January 2024. It is no longer hosted or updated.\n\n3. StreamSets\nIBM completed its acquisition in July 2024. It now sits inside IBM's wider data integration suite.\n\n4. Cloudera CDH and HDP\nBoth are past end of support. On-prem Cloudera 7.3.1 reaches end of support in December 2026.\n\nNone of this makes these tools bad. Plenty of pipelines run on them today, and run well.\n\nBut a new owner or a closing support window changes the renewal conversation. You have three options:\n\n→ Stay and pay for extended support. It buys time, not a plan.\n→ Move to the vendor's cloud. Same vendor, new platform, new contract.\n→ Own the logic. Convert the pipelines to open code that lives in your own repo.\n\nWhich one is your team planning for?\n\nSources: Salesforce, Qlik, IBM, Cloudera support lifecycle. PowerCenter dates per Informatica's lifecycle guide.\n\n#DataEngineering #ETL #DataLeadership",
   "first_comment": "",
   "sources": [
    "Salesforce press release 18 Nov 2025",
    "Qlik Talend Open Studio page",
    "IBM newsroom 1 Jul 2024",
    "Cloudera support lifecycle page",
    "PowerCenter 10.5 date: LIKELY, confirm with Informatica lifecycle guide before publishing"
   ],
   "numbers_for_signoff": [
    "All dates"
   ],
   "short": "Legacy ETL tools changed hands"
  },
  {
   "id": "C5",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-04",
   "time": "10:00",
   "idea": "N8: three kinds of people do data engineering",
   "format": "Single image · 3-circle Venn with intersections",
   "sample": {
    "id": "AV40",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Proportional 3-circle Venn, labelled pairwise intersections, center thesis, numbered rule cards",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7460627938871418880"
   },
   "copy_basis": "Sample AV40's copy (what each circle does, what breaks where two overlap, the rules we run by).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "C5",
    "tall": false,
    "files": [
     "media/C5/image.jpg?v=202610010132"
    ]
   },
   "text": "Three kinds of people do data engineering. Only one of them has it in their job title.\n\nThe data engineer\nCarries a backlog from every team. Owns what reaches production. Wants the design work back.\n\nThe analyst who never signed up for it\nHas to join sources and work out why two numbers disagree before the real analysis can start.\n\nThe product team whose app runs on data\nNeeds data plumbing under the product. Builds it once, then maintains it forever.\n\nWhere they overlap is where the pain lives:\n\n→ Two sources disagree, and reconciliation belongs to nobody\n→ A field means one thing in the report and another in the app\n→ The app depends on pipelines its own team never designed\n\nWe built BigHammer.ai for all three, on one shared foundation:\n\n1. Meaning stays attached. A field means the same thing in the pipeline, the report and the app.\n2. AI where it helps. Fixed, predictable rules wherever the workflow needs them.\n3. Logic in your repo. The business knowledge you build stays in your own GitHub.\n\nWhich of the three are you, most weeks?\n\n#DataEngineering #Analytics #AI",
   "first_comment": "",
   "sources": [
    "Richard Lawrence, 'general overview' doc: three audiences, context engine, deterministic rules, customer GitHub"
   ],
   "numbers_for_signoff": [],
   "short": "3 kinds of people do DE"
  },
  {
   "id": "C6",
   "profile": "company",
   "status": "ready",
   "date": "2026-10-02",
   "time": "10:00",
   "idea": "N9: Databricks Budgets are GA; tags decide if they work",
   "format": "Single image · vertical flowchart branching into tiers",
   "sample": {
    "id": "AV26",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Single-column pipeline of step cards with tool chips, branching into 3 tier cards, final sync box, dashed feedback loop",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7467876018767196160"
   },
   "copy_basis": "Sample AV26's step-by-step system copy (Step 1 to 6 with the why under each, closing line, question).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "C6",
    "tall": false,
    "files": [
     "media/C6/image.jpg?v=202610010132"
    ]
   },
   "text": "Databricks Budgets went GA in July.\n\nMost teams will set one budget for the whole account. It will tell them almost nothing.\n\nA budget is only as useful as the tags underneath it. Here's the order that works:\n\n1. Pick three tags. No more.\nowner, cost_center, environment.\n\n2. Enforce them with a cluster policy.\nA policy can require a cost centre tag before compute will launch. No tag, no cluster.\n\n3. Fix the spend that can't carry a tag.\nScheduled work on All-Purpose clusters moves to job compute, so every run is traceable.\n\n4. Check tag coverage in system.billing.usage.\nWhat share of spend actually carries the tags? That's your real starting line.\n\n5. Now create budgets, per tag.\nOne per team. One per environment, because non-prod is where drift hides. A monthly showback by owner for the top 10 jobs.\n\nThen review spend against the value it delivered, every month.\n\nAnd report untagged spend as a visibility gap. Never as savings.\n\nWhat share of your spend carries an owner tag today?\n\n#Databricks #FinOps #CloudCost",
   "first_comment": "",
   "sources": [
    "Databricks release notes Jul 2026: Budgets GA",
    "Databricks cluster policy docs: required COST_CENTER tag example",
    "BigHammer email series Issue 2"
   ],
   "numbers_for_signoff": [],
   "short": "Budgets need tags"
  },
  {
   "id": "S1",
   "profile": "srinath",
   "status": "ready",
   "date": "2026-10-02",
   "time": "10:00",
   "short": "Azure Standard tier is gone",
   "idea": "W1: Azure Databricks Standard tier auto-upgraded to Premium on 1 Oct",
   "format": "Single image · editorial news-article mimicry",
   "sample": {
    "id": "AV19",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Editorial article stack: kicker, headline, date, standfirst, share row, illustrated hero, credit line",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7471136784983293952"
   },
   "copy_basis": "Prompt doc: News Post template (news hook, impact line, numbered analysis blocks, engagement question), in Srinath's story-first voice.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "S1",
    "tall": false,
    "files": [
     "media/S1/image.jpg?v=202610010132"
    ]
   },
   "text": "Yesterday, Microsoft moved every Azure Databricks workspace still on Standard tier to Premium.\n\nAutomatically. Nobody on your team had to click a thing.\n\nHere is why I think it matters more than it looks.\n\n1. The rate changed. The workload did not.\nSame jobs, same clusters, same schedules. A different tier. If you were still on Standard, compare what you pay per DBU now with last month.\n\n2. Access controls start switched off.\nMicrosoft's own docs say access control lists are disabled by default on upgraded workspaces. Worth a look from your platform team this week.\n\n3. Month one is where surprises hide.\nDatabricks made Budgets generally available in July. Set one on these workspaces now, so the first Premium invoice is not a surprise.\n\nNone of this is a problem with Databricks. The platform did exactly what was announced.\n\nThe problem is the one I see everywhere. Changes land on the bill before anyone looks at the bill.\n\nOn 15 October I am running a live masterclass on how to baseline your spend, so changes like this never catch you out.\n\nWere any of your workspaces still on Standard?\n\n#Databricks #Azure #FinOps",
   "first_comment": "If Azure Databricks is part of your estate, this is exactly the kind of change I will show you how to catch early. Live masterclass, Thu 15 Oct, 12:00 PM ET. Save your seat: https://webinar.bighammerai.com/",
   "sources": [
    "Microsoft Learn: Azure Databricks Standard tier retirement (dated 11 Sep 2026): auto-upgrade 1 Oct 2026, ACLs disabled by default after upgrade",
    "Databricks release notes Jul 2026: Budgets GA"
   ],
   "numbers_for_signoff": []
  },
  {
   "id": "S2",
   "profile": "srinath",
   "status": "ready",
   "date": "2026-10-05",
   "time": "10:00",
   "short": "Is that savings number real?",
   "idea": "W4: every vendor promises 75%, including us. 4 questions to check any of us",
   "format": "Single image · quote card",
   "sample": {
    "id": "AB21",
    "creator": "Austin Belcak",
    "what": "Minimal quote card: speckled paper, avatar + name row, one large sentence",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7471910820696891392"
   },
   "copy_basis": "Prompt doc: Thought Leadership template (question, bold answer, value, proof, italic key line, emoji bullets, close).",
   "cta": true,
   "media": {
    "type": "image",
    "src": "S2",
    "tall": false,
    "files": [
     "media/S2/image.jpg?v=202610010132"
    ]
   },
   "text": "How do you know if a savings number is real?\n\nASK WHAT WAS MEASURED.\n\nEvery vendor in my space promises you 75%. Including us. After the third deck, leadership stops listening. And they are right to.\n\nI have sat on both sides of this table. Buying tools for a 600+ person data organization, and now building one.\n\n*If a savings number cannot tell you what was measured and what was assumed, it is not a number. It is a pitch.*\n\nSo here are the 4 questions I would ask any vendor, including us:\n\n🔍 What was measured from your own billing and run data?\n\n🧮 What was assumed, and at what rate?\n\n🚫 What was left out? Contract discounts, cloud VM costs, spend nobody can trace to a job.\n\n➕ Could the total savings be bigger than what you actually spend? If that is not an obvious no, something is counted twice.\n\nThat is why our reports keep two columns. Measured first. Estimates second, each with the rule behind it. And spend we cannot trace is never called savings.\n\nOn 15 October I will show you which parts of our numbers are measured and which are estimated. Live.\n\n#Databricks #FinOps #DataLeadership",
   "first_comment": "Want to see the measured versus estimated split on a real Databricks bill? That is exactly what I walk through live on Thu 15 Oct, 12:00 PM ET. Join here: https://webinar.bighammerai.com/",
   "sources": [
    "BigHammer email series Issue 5 (measured vs estimated, 4 questions)",
    "voice.md: 600+ people across data engineering, governance and data quality at D&B"
   ],
   "numbers_for_signoff": [
    "75% (vendor claim reference)",
    "600+ person organization"
   ]
  },
  {
   "id": "S3",
   "profile": "srinath",
   "status": "ready",
   "date": "2026-10-07",
   "time": "10:00",
   "short": "The free AirPods confession",
   "idea": "W10: half my old team signed up for webinars for the free AirPods",
   "format": "Single image · photo hero, message on a phone screen",
   "sample": {
    "id": "HD05",
    "creator": "Harry Dry (@marketingharry)",
    "what": "Photo hero: the message lives on the lit screen of a device held in hand (message-as-device-screen)",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7478310902824546304"
   },
   "copy_basis": "Prompt doc: Experiential Story template (hook, context, struggle, turning point, decision with a real quote, value, outcome, close). Re-matched from AB35 to HD05 after design review: no candid photo of Srinath exists, so the story is carried by an object photo (no person, AI generated) with his words on the screen.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "S3v2",
    "tall": false,
    "files": [
     "media/S3v2/image.jpg?v=202610010132"
    ]
   },
   "text": "Half my old team signed up for webinars for the free AirPods.\n\nI never blamed them.\n\nMost of those webinars were a sales pitch with a title slide. Forty minutes about the product, five minutes of anything useful, and a gift card at the end to make the hour feel worth it.\n\nSome of them told me straight. They stayed for the giveaway, not the content.\n\nSo when we started planning our own masterclass, I kept thinking about them.\n\nRichard Lawrence, who works with me at BigHammer.ai, said it best in one of our planning calls:\n\n\"If it comes in the middle, this is just a product pitch.\"\n\nHe was right. So we flipped it.\n\n30 minutes of the framework we actually use to bring Databricks costs down. Real numbers. Then 15 minutes of your questions. BigHammer only shows up at the very end.\n\nThere is still a prize. The three best questions win a $50 Amazon gift card. I would rather reward a good question than a long attention span.\n\nIf you own a Databricks bill, I would love to see you there on Thursday 15 October.\n\nBring your hardest question.",
   "first_comment": "Thursday 15 October at 12:00 PM ET. It's free: 30 minutes of the framework, 15 minutes of your questions, and the pitch saved for the last minute. Grab a seat: https://webinar.bighammerai.com/",
   "sources": [
    "10 Jun planning call transcript: Srinath on team attending webinars for free AirPods / gift cards; Richard: 'if it comes in the middle, this is just a product pitch'",
    "Webinar page: structure, $50 gift card for top 3 questions"
   ],
   "numbers_for_signoff": [
    "$50 gift card, top 3 questions"
   ]
  },
  {
   "id": "S4",
   "profile": "srinath",
   "status": "ready",
   "date": "2026-10-03",
   "time": "10:00",
   "short": "Automate the upkeep, keep the engineer",
   "idea": "N1: customers feared automation meant layoffs. I respect that answer",
   "format": "Single image · hand-drawn crossing-curves chart",
   "sample": {
    "id": "HD49",
    "creator": "Harry Dry (@marketingharry)",
    "what": "Hand-drawn line chart, two crossing curves, numbered call-outs, end labels, share box",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7459865898087092224"
   },
   "copy_basis": "Prompt doc: Thought Leadership template, opened as a story (Srinath is story-first); sample HD49 is image-led so its one-line copy was not enough.",
   "cta": false,
   "media": {
    "type": "image",
    "src": "S4",
    "tall": false,
    "files": [
     "media/S4/image.jpg?v=202610010132"
    ]
   },
   "text": "A few customers told us they did not want to automate because it might mean laying off data engineers.\n\nI respect that answer. It comes from leaders who care about their people.\n\nI ran a data organization of more than 600 people. I know how a team feels when the word automation shows up on a slide.\n\nBut here is what I have seen. The work that gets automated first is not the work engineers love. It is the upkeep.\n\nFailed overnight jobs. Reruns. Schema breaks. Manual checks.\n\nOne benchmark this year put fragile pipelines and manual operations at 53% of engineering time. More than half the week, spent keeping things standing.\n\nGartner expects agentic data management to automate 75% of data engineering workflows by 2029. That change is coming either way.\n\nSo the real question for a leader is not \"will we automate\". It is \"where will my people go when we do\".\n\nMy answer: closer to the business.\n\nDesign. Business logic. Data products. Getting data ready for AI.\n\nThat is where engineers grow. It is also where the business has been waiting for them.\n\nAutomate the upkeep. Keep the engineer.\n\nIf you lead a data team, what would your engineers build with half their week back?\n\n#DataEngineering #Leadership #AI",
   "first_comment": "",
   "sources": [
    "Questions for Context: customers feared automation meant laying off data engineers",
    "Fivetran 2026 enterprise data infrastructure benchmark: 53% of engineering time (vendor survey, n=500)",
    "Gartner VP Analyst via CIO&Leader, 24 Sep 2026: 75% of DE workflows automated by 2029"
   ],
   "numbers_for_signoff": [
    "53%",
    "75% by 2029",
    "600+"
   ]
  },
  {
   "id": "S5",
   "profile": "srinath",
   "status": "ready",
   "date": "2026-10-04",
   "time": "10:00",
   "short": "Snowflake Gen2: faster, cheaper?",
   "idea": "N4: a faster Snowflake warehouse can cost more. The math",
   "format": "Single image · dark comparison table + worked example",
   "sample": {
    "id": "AV20",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Dark comparison table: factor column, colored channel headers with icons, cell text, face footer",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7470774398262865920"
   },
   "copy_basis": "Srinath technical structure (problem, fix, result) with the sample's factor-by-factor logic; prompt-doc Thought Leadership rhythm for the opening.",
   "cta": false,
   "media": {
    "type": "image",
    "src": "S5",
    "tall": false,
    "files": [
     "media/S5/image.jpg?v=202610010132"
    ]
   },
   "text": "A faster warehouse can cost you more. Here is the math.\n\nSnowflake's Gen2 warehouses are genuinely faster engines. They also burn more credits per hour. 1.35x on AWS and GCP. 1.25x on Azure.\n\nSo which one is cheaper? It depends on one thing.\n\nCost is credits per hour, times the hours the warehouse runs. That is it.\n\nTake a job that runs for 60 minutes on a Medium Gen1 warehouse. That is 4 credits.\n\nOn Gen2 in AWS, the same job has to finish in about 44 minutes to cost the same. On Azure, about 48.\n\nFaster than that, Gen2 wins. Slower, and the faster warehouse is the expensive one.\n\nTwo more things worth knowing:\n\n→ Every time a warehouse resumes, you pay for at least 60 seconds. On either generation.\n→ Gen2 is not the default yet, and not in every region. You opt in.\n\nThe fix is simple. Run the same queries on both for a week. Compare WAREHOUSE_METERING_HISTORY and QUERY_HISTORY. Let the numbers decide.\n\nI say this about every platform. Match the engine to the job, then check the bill.\n\nHave you tested Gen2 against your own workloads yet?\n\n#Snowflake #FinOps #DataEngineering",
   "first_comment": "",
   "sources": [
    "Snowflake Credit Consumption Table (effective 30 Sep 2026): Gen2 1.35x AWS/GCP, 1.25x Azure; 60 s minimum on resume",
    "Snowflake docs: Gen2 not default, not all regions; account usage views"
   ],
   "numbers_for_signoff": [
    "1.35x / 1.25x",
    "4 credits Medium",
    "44 / 48 min break-even",
    "60 s minimum"
   ]
  },
  {
   "id": "S6",
   "profile": "srinath",
   "status": "ready",
   "date": "2026-10-06",
   "time": "10:00",
   "short": "Spark 4.0: 3 silent migration risks",
   "idea": "W8: Spark 4.0 changes 3 things your migration tests won't catch",
   "format": "Carousel · 8 slides, dark tutorial with code windows",
   "sample": {
    "id": "AB34",
    "creator": "Austin Belcak",
    "what": "Dark tutorial carousel: identity header on every slide, highlighted title phrase, UI screenshots, CTA slide",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7477346638710190080"
   },
   "copy_basis": "Prompt doc: Carousel template (strong opener, belief challenge, what's inside, CTA), in Srinath's voice. Slide text follows the carousel slide template (numbered steps, one idea per slide, CTA slide).",
   "cta": true,
   "media": {
    "type": "carousel",
    "src": "S6",
    "title": "Spark 4.0: 3 silent migration risks + 5 parity checks",
    "files": [
     "media/S6/p01.jpg?v=202610010132",
     "media/S6/p02.jpg?v=202610010132",
     "media/S6/p03.jpg?v=202610010132",
     "media/S6/p04.jpg?v=202610010132",
     "media/S6/p05.jpg?v=202610010132",
     "media/S6/p06.jpg?v=202610010132",
     "media/S6/p07.jpg?v=202610010132",
     "media/S6/p08.jpg?v=202610010132"
    ]
   },
   "text": "Spark 4.0 changed what happens when you cast 'abc' to a number.\n\nOn an older Databricks cluster, you get NULL. On Spark 4.0, the job fails.\n\nThat one change matters right now. EMR 8.0 and Dataproc 3.0 both run Spark 4.0. If you are moving jobs off Databricks this year, that is where they land.\n\nYou will hear this a lot:\n\n\"The code converted fine.\"\n\"All the tests passed.\"\n\"The job ran successfully.\"\n\nBut a job can run on time and still produce different numbers.\n\nInside the carousel:\n\n1. Why the target platforms changed under you\n2. ANSI mode, where bad input now stops the job\n3. Time zones, where the same row lands on a different day\n4. The Databricks only calls to replace first\n5. The 5 parity checks I would run on every migrated job\n6. How to run them without touching production\n\nCode conversion is the visible part of a migration. Proving parity is where trust is won or lost.\n\nOn 15 October I am walking through the full assess, migrate, monitor playbook, live.\n\nSave this for your next migration planning meeting.\n\n#Spark #Databricks #DataEngineering",
   "first_comment": "Planning a move to EMR or Dataproc this year? I cover the parity checks and the migration waves in detail on Thu 15 Oct, 12:00 PM ET. Join me: https://webinar.bighammerai.com/",
   "sources": [
    "Apache Spark SQL migration guide: ANSI on by default since 4.0",
    "Databricks docs: ANSI default from DBR 17.0; dbutils, dlt, Connect, UC names",
    "AWS: EMR 8.0 Spark 4.0 GA 9 Jun 2026; Google: Dataproc image 3.0 GA 15 Jul 2026",
    "BigHammer email series Issue 8 (parity checks)"
   ],
   "numbers_for_signoff": []
  },
  {
   "id": "R4",
   "profile": "richard",
   "status": "ready",
   "date": "2026-10-02",
   "time": "10:00",
   "short": "What walks out the door",
   "idea": "N7: when your best data engineer leaves, the most valuable thing can leave with them",
   "format": "Single image · hand-drawn iceberg",
   "sample": {
    "id": "HD50",
    "creator": "Harry Dry (@marketingharry)",
    "what": "Hand-drawn iceberg: small 'what people think' tip, dense grid of rounded bubbles below the waterline, labels with arrows, closing banner",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7459499258191237120"
   },
   "copy_basis": "Prompt doc: Viral Quotes (empowerment) template: hook, pattern interrupt, core message, misconception list, bridge, pain points, lessons, closing truth. HD50's own copy is a one-liner, too thin for Richard's point.",
   "cta": false,
   "media": {
    "type": "image",
    "src": "R4",
    "tall": false,
    "files": [
     "media/R4/image.jpg?v=202610010132"
    ]
   },
   "text": "When a senior data engineer hands in their notice, most companies worry about the code.\n\nHere's the thing.\n\nThe code is the easy part.\n\nIt's still there on Monday. What leaves is everything the code means:\n\n• Why that join exists\n• Which report the CFO actually trusts\n• What \"active customer\" means in this company\n• The workaround that keeps the 2am job alive\n• Who to call when a source system changes\n\nNone of that is written down. It lives in one person's head, and in pipeline logic that only they can read.\n\nI spent years selling data integration tools. I watched this happen at customer after customer. A good engineer left, and a quarter of \"why does this number look wrong?\" followed.\n\nThe fix isn't to stop people leaving. People should grow and move on.\n\nThe fix is where the knowledge lives.\n\nBusiness rules belong in your own repository, in plain view, where the next person can read them and the business can own them.\n\nYour engineers will always move on.\nYour logic shouldn't have to.\n\n#DataEngineering #DataLeadership #DataGovernance",
   "first_comment": "",
   "sources": [
    "Richard Lawrence 'general overview' doc: customer knowledge and logic kept in the customer's GitHub repository",
    "Richard Lawrence 'switch to enterprise' doc: career selling data integration (Talend, Pentaho, StreamSets)"
   ],
   "numbers_for_signoff": []
  },
  {
   "id": "R2",
   "profile": "richard",
   "status": "ready",
   "date": "2026-10-03",
   "time": "10:00",
   "short": "Talend Open Studio was retired",
   "idea": "N5: I used to sell Talend. The free edition many teams started on was retired",
   "format": "Single image · editorial article page",
   "sample": {
    "id": "AB43",
    "creator": "Austin Belcak",
    "what": "Newspaper article screenshot: headline, standfirst, byline, date, photo with caption",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7470098881352052736"
   },
   "copy_basis": "Prompt doc: Experiential Story template (hook, context, struggle, turning point, decision, value, outcome, close). No emojis, lots of whitespace.",
   "cta": false,
   "media": {
    "type": "image",
    "src": "R2",
    "tall": false,
    "files": [
     "media/R2/image.jpg?v=202610010132"
    ]
   },
   "text": "I used to sell Talend.\n\nSo I remember how many data teams started with the free version.\n\nTalend Open Studio was the easy yes. No procurement, no budget meeting. Download it, build a few jobs, prove the idea. Then a few jobs became a few hundred, and the proof of concept quietly became production.\n\nOn 31 January 2024, Qlik retired it.\n\nIt's no longer hosted or updated. The jobs built on it didn't stop running. They just stopped getting patches.\n\nI don't say this to criticise anyone. Starting free was a sensible decision at the time, and I sold plenty of upgrades off the back of it.\n\nBut from the seller's side of the table, I learned something I wish more buyers knew.\n\nThe tool you start on for free often becomes the tool you can't leave. Not because it's the best option, but because your business logic is locked inside it.\n\nIf you still have Open Studio jobs in your estate, three questions are worth an hour this month:\n\nWhich jobs still run on it?\nWho could patch them if they broke?\nWhere should that logic live next?\n\nThe answers usually say more about your platform strategy than any vendor roadmap.\n\n#DataEngineering #ETL #DataLeadership",
   "first_comment": "",
   "sources": [
    "Qlik Talend Open Studio page: retired 31 Jan 2024, no longer hosted or updated",
    "Richard Lawrence 'switch to enterprise' doc: sold Talend, Pentaho, StreamSets"
   ],
   "numbers_for_signoff": []
  },
  {
   "id": "R3",
   "profile": "richard",
   "status": "ready",
   "date": "2026-10-04",
   "time": "10:00",
   "short": "The Worried vs The Curious",
   "idea": "N2: two kinds of reaction when data engineers meet AI",
   "format": "Carousel · 10 slides, dark post-card comparison",
   "sample": {
    "id": "AB17",
    "creator": "Austin Belcak",
    "what": "Dark fake-post carousel: avatar + name on every card, alternating two types, one idea per slide",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7472695994456100864"
   },
   "copy_basis": "Sample AB17's own copy structure ('There are two types of...', which one are you?) beat the prompt-doc Carousel template for a comparison story.",
   "cta": false,
   "media": {
    "type": "carousel",
    "src": "R3",
    "title": "The Worried vs The Curious",
    "files": [
     "media/R3/p01.jpg?v=202610010132",
     "media/R3/p02.jpg?v=202610010132",
     "media/R3/p03.jpg?v=202610010132",
     "media/R3/p04.jpg?v=202610010132",
     "media/R3/p05.jpg?v=202610010132",
     "media/R3/p06.jpg?v=202610010132",
     "media/R3/p07.jpg?v=202610010132",
     "media/R3/p08.jpg?v=202610010132",
     "media/R3/p09.jpg?v=202610010132",
     "media/R3/p10.jpg?v=202610010132"
    ]
   },
   "text": "There are two kinds of data engineers meeting AI right now.\n\nThe Worried and The Curious.\n\nBoth are smart. Both work hard. One is about to have a much better couple of years.\n\nThe Worried see AI as a threat to skills they spent years building. That's an understandable reaction, but it tends to end with every conversation being about what could go wrong.\n\nThe Curious ask a different question: how could this help me do more?\n\nThey don't trust it blindly. In last year's Stack Overflow survey only a third of developers said they trust the accuracy of AI output. So they check the work and keep their own judgement.\n\nBut they hand over the repetitive upkeep, and spend the time they get back closer to the business.\n\nSwipe through for the differences.\n\nAt BigHammer.ai, the second mindset is the one we most want to work with. Automating the mundane work is where it starts. Human judgement stays at the centre.\n\nWhich one sounds more like your team?\n\n#DataEngineering #AI #DataTeams",
   "first_comment": "",
   "sources": [
    "Richard Lawrence 'The Data Engineers We Want to Work With' doc",
    "Stack Overflow Developer Survey 2025: 33% trust AI accuracy, 66% 'almost right, but not quite'"
   ],
   "numbers_for_signoff": [
    "33%"
   ]
  },
  {
   "id": "R1",
   "profile": "richard",
   "status": "ready",
   "date": "2026-10-05",
   "time": "10:00",
   "short": "Your renewal was on my forecast",
   "idea": "W6: when I sold software, your renewal sat on my forecast as an expansion opportunity",
   "format": "Single image · post card over lifestyle photo",
   "sample": {
    "id": "AB03",
    "creator": "Austin Belcak",
    "what": "White rounded post card floating over the upper third of a full-bleed lifestyle photo of the author",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7479520965937467392"
   },
   "copy_basis": "Prompt doc: Experiential Story template: confession hook, context, turning point, what buyers should do, close.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "R1",
    "tall": false,
    "files": [
     "media/R1/image.jpg?v=202610010132"
    ]
   },
   "text": "When I sold software, your renewal date sat on my forecast.\n\nNot as a date. As an \"expansion opportunity\".\n\nI'm not proud of every conversation that followed. A new version meant a chance to charge more. The deal was on the forecast, and the forecast had to close.\n\nWhat made those renewals easy for the seller was simple. The buyer usually arrived with one number: the invoice total.\n\nA total isn't evidence. It tells you what you spent. It doesn't tell you what drove it, what's growing, or what could run somewhere cheaper.\n\nIf you're heading into a data platform renewal this year, here's what I'd want you to bring:\n\n1. A 90-day cost baseline you can defend line by line\n2. Your top 10 jobs by cost, each with an owner\n3. What failed runs cost you, on a separate line\n4. Which workloads genuinely need the platform, and which don't\n\nThat last one is your leverage.\n\nWith those four, the conversation stops being about the price and starts being about your workloads. That's a much stronger seat to sit in.\n\nI switched sides because I wanted success to come from customers seeing real value in what they buy.\n\nThis is what that looks like in practice. If you want help building that evidence, there's a free masterclass on it in the comments.\n\n#DataLeadership #Databricks #FinOps",
   "first_comment": "On Thursday 15 October, our founder and CEO Srinath Reddy is running a free live masterclass on building exactly this evidence for a Databricks renewal, using real billing data. 45 minutes, 12:00 PM ET / 5 PM UK. Save a seat: https://webinar.bighammerai.com/",
   "sources": [
    "Richard Lawrence 'switch to enterprise' doc (forecast, expansion opportunity, customer value)",
    "BigHammer email series Issue 1 (renewal evidence checklist)"
   ],
   "numbers_for_signoff": [
    "90-day baseline",
    "top 10 jobs"
   ]
  },
  {
   "id": "R5",
   "profile": "richard",
   "status": "ready",
   "date": "2026-10-06",
   "time": "10:00",
   "short": "Price all four bills",
   "idea": "N11: before you move a job, price all four bills",
   "format": "Single image · checklist infographic",
   "sample": {
    "id": "PC21",
    "creator": "Patrick James Cumming (Ad Juice)",
    "what": "Launch checklist: bold header bar, 4 numbered dark-headed sections of checkboxes, code chips, dark 'gut check' box",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7465356172951240704"
   },
   "copy_basis": "Sample PC21's own copy (checklist framing, why it matters, the list, resource CTA) adapted; prompt-doc Case Study rhythm for the setup.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "R5",
    "tall": false,
    "files": [
     "media/R5/image.jpg?v=202610010132"
    ]
   },
   "text": "Most migration business cases I've seen price one bill.\n\nThe new platform's compute.\n\nIt looks great on a slide. Then the real costs turn up, and the savings that justified the project shrink by the quarter.\n\nBefore you move any job to a new platform, price all four bills:\n\n1. Target compute\nSized from real utilisation data, not last year's cluster size. Spot capacity where a retry is cheap. Egress if the data crosses clouds.\n\n2. The platform fee\nManaged Spark isn't just the machines. Google Dataproc adds $0.010 per vCPU hour on top of the Compute Engine bill. Amazon EMR adds a per-instance uplift, around $0.048 an hour on an m5.xlarge in us-east-1.\n\n3. Migration effort\nConverting platform-specific code, rewiring orchestration and rebuilding access and governance. Priced per job, not per project.\n\n4. The dual-run period\nWhile you prove the new job matches the old one, you pay for both.\n\nThen do the 60-second check before anyone signs:\n\n→ Every job has a 90-day cost baseline\n→ Fees are counted on both sides\n→ Dual-run weeks are in the budget\n→ Savings are split into measured and estimated\n→ Jobs that belong where they are, stay there\n\nA business case that survives those five questions is one your CFO will still believe in a year.\n\nSave this for your next platform review.\n\n#DataEngineering #FinOps #CloudCost",
   "first_comment": "If you're building a business case for a Databricks renewal or a move this year, our founder and CEO Srinath Reddy walks through how to price it properly in a free live masterclass on Thursday 15 October, 12:00 PM ET / 5 PM UK. Save a seat: https://webinar.bighammerai.com/",
   "sources": [
    "Google Cloud Dataproc pricing: $0.010 per vCPU hour",
    "AWS EMR pricing: m5.xlarge EMR uplift $0.048/hr us-east-1",
    "BigHammer email series Issues 7 and 8"
   ],
   "numbers_for_signoff": [
    "$0.010 per vCPU hour",
    "$0.048 per hour"
   ]
  },
  {
   "id": "R6",
   "profile": "richard",
   "status": "ready",
   "date": "2026-10-07",
   "time": "10:00",
   "short": "Please don't come if...",
   "idea": "W11: please don't come to our masterclass on 15 October if any of these are true",
   "format": "Carousel · 7 slides, dark glass with 3D objects",
   "sample": {
    "id": "AV41",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Dark glass carousel: spotlit 3D hero object, numbered title box, glass sub-card, bold takeaway, profile card on the last slide",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7460265778966204417"
   },
   "copy_basis": "Sample AV41's copy shape (bold claim, numbered reasons with a one-line payoff each, 'worth checking out' close) as a reverse-psychology event promotion; prompt-doc Carousel template for the CTA slide.",
   "cta": true,
   "media": {
    "type": "carousel",
    "src": "R6",
    "title": "Please don't come to our masterclass if...",
    "files": [
     "media/R6/p01.jpg?v=202610010132",
     "media/R6/p02.jpg?v=202610010132",
     "media/R6/p03.jpg?v=202610010132",
     "media/R6/p04.jpg?v=202610010132",
     "media/R6/p05.jpg?v=202610010132",
     "media/R6/p06.jpg?v=202610010132",
     "media/R6/p07.jpg?v=202610010132"
    ]
   },
   "text": "Please don't come to our masterclass on 15 October if any of these are true.\n\nI mean it. I spent years inviting people to webinars that weren't for them, and I'd rather not waste your Thursday.\n\nSkip it if:\n\n1. Your platform bill is small and flat\n2. Every cluster already has an owner, a tag and a timeout\n3. You already know your cost per job\n4. You're hoping for a product demo\n\nThat last one matters. It's 30 minutes of framework and 15 minutes of your questions. BigHammer.ai only comes up in the final minute.\n\nStill here? Then it's probably for you:\n\n→ Data leaders whose platform bill keeps climbing\n→ Platform owners with a renewal coming up\n→ FinOps teams asked to explain the spend\n→ Engineering managers planning a move to EMR or Dataproc\n\nOur founder and CEO, Srinath Reddy, is hosting it live. Swipe through, and the link is in the first comment.\n\n#Databricks #FinOps #DataEngineering",
   "first_comment": "Thursday 15 October, 12:00 PM ET / 5 PM UK. A free 45-minute masterclass with Srinath Reddy, founder and CEO of BigHammer.ai, on reducing Databricks costs by up to 75%. Bring your hardest cost question: the best three win a $50 Amazon gift card. Save a seat: https://webinar.bighammerai.com/",
   "sources": [
    "Webinar page: structure (30 + 15 minutes), $50 gift card for top 3 questions, 'up to 75%' title",
    "Deck slides 2-8: audience roles"
   ],
   "numbers_for_signoff": [
    "up to 75%",
    "$50 gift card"
   ]
  },
  {
   "id": "T4",
   "profile": "terry",
   "status": "ready",
   "date": "2026-10-02",
   "time": "10:00",
   "short": "Serverless: Standard vs Performance",
   "idea": "N10: a serverless jobs setting that can make the same job up to 70% cheaper",
   "format": "Single image · two stacked comparison panels",
   "sample": {
    "id": "PC34",
    "creator": "Patrick James Cumming (Ad Juice)",
    "what": "Two stacked panels (inconsistent vs consistent), each an isotype grid with labelled tabs and stat bars",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7452672576859947009"
   },
   "copy_basis": "Sample PC34's own copy structure (common assumption, the real driver, when it applies and when it doesn't, the better default).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "T4",
    "tall": false,
    "files": [
     "media/T4/image.jpg?v=202610010132"
    ]
   },
   "text": "Most teams on Databricks serverless jobs never touch one setting.\n\nIt's called the performance mode, and it quietly decides how much each run costs.\n\nPerformance optimized starts your job in under a minute.\n\nStandard mode takes 4 to 6 minutes to start. In exchange, Databricks says it can be up to 70% cheaper for some workloads. Same SKU, same list price. It simply uses fewer DBUs.\n\nSo which one should you use? It depends on the deadline, not the job.\n\nAn overnight batch that has to be done by 6am?\nA few extra minutes of startup at 2am changes nothing. Standard mode is the easy pick.\n\nA job with a 15-minute SLA?\nFive minutes of startup eats a third of the window. Pay for fast startup.\n\nThe mistake I see most often is one default for everything. Usually the fast one, because nobody wants to be the person who slowed a pipeline down.\n\nA better default: start every scheduled batch job on Standard, and only switch to Performance optimized when an SLA actually needs it.\n\nHow many of your serverless jobs genuinely need to start in under a minute?\n\n#Databricks #Serverless #FinOps",
   "first_comment": "",
   "sources": [
    "Databricks docs: serverless jobs performance modes (Standard 4-6 min startup, 'up to 70% cheaper for some workloads'; same SKU; GA June 2025)"
   ],
   "numbers_for_signoff": [
    "up to 70%",
    "4-6 min"
   ]
  },
  {
   "id": "T5",
   "profile": "terry",
   "status": "ready",
   "date": "2026-10-03",
   "time": "10:00",
   "short": "Genie is free until 31 January",
   "idea": "N12: Databricks Genie is free until 31 January 2027. Plan the bill now",
   "format": "Single image · 3-phase timeline",
   "sample": {
    "id": "PC24",
    "creator": "Patrick James Cumming (Ad Juice)",
    "what": "3-phase workflow: month columns with numbered step cards, highlighted final phase, day rail underneath",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7463544216900771841"
   },
   "copy_basis": "Sample PC24's own copy structure (context, then Phase 1 / 2 / 3 with what happens in each, closing lesson).",
   "cta": false,
   "media": {
    "type": "image",
    "src": "T5",
    "tall": false,
    "files": [
     "media/T5/image.jpg?v=202610010132"
    ]
   },
   "text": "Databricks Genie is free until 31 January 2027.\n\nThat's the best time to plan what it will cost.\n\nIn July, Databricks moved Genie to pay-as-you-go. A week later it paused billing for Genie One and Genie Agents until the end of January.\n\nFree tools spread fast. By the time the meter starts, usage will have grown well past what anyone planned for.\n\nHere's how I'd use the next four months:\n\n1. Measure (October)\nList every Genie space and the team behind it. Baseline who uses it and how often. Note what it answers well, and what it doesn't.\n\n2. Govern (November and December)\nGive every space a named owner. Set budgets per team: Databricks Budgets went GA in July. Agree what \"good value\" looks like before anyone argues about the invoice.\n\n3. Decide (January)\nKeep the spaces people rely on. Retire the ones nobody opens. Have alerts live before 31 January.\n\nThe State of FinOps 2026 report found 98% of FinOps teams now manage AI spend, up from 63% a year earlier. AI costs have moved from experiment to line item.\n\nThe teams that plan in the free months won't be surprised in February.\n\n#Databricks #FinOps #AI",
   "first_comment": "",
   "sources": [
    "Databricks release notes Jul 2026: Genie pay-as-you-go (8 Jul), Genie One + Genie Agents billing paused until 31 Jan 2027 (15 Jul), Budgets GA (6 Jul)",
    "FinOps Foundation State of FinOps 2026: 98% manage AI spend (63% in 2025)"
   ],
   "numbers_for_signoff": [
    "98%",
    "63%"
   ]
  },
  {
   "id": "T6",
   "profile": "terry",
   "status": "ready",
   "date": "2026-10-04",
   "time": "10:00",
   "short": "AI agents move data. Transform?",
   "idea": "N3: AI agents can move data almost perfectly. Transforming it is a different story",
   "format": "Carousel · 7 slides, surreal cover + % breakdown",
   "sample": {
    "id": "HD40",
    "creator": "Harry Dry (@marketingharry)",
    "what": "Surreal 3D metaphor cover, heavy condensed headlines, percentage breakdown bars, one idea per slide",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7463526212997406720"
   },
   "copy_basis": "Prompt doc: Thought Leadership template (question, bold answer, value, proof, key line, breakdown, close). HD40's own copy is a one-line teaser.",
   "cta": false,
   "media": {
    "type": "carousel",
    "src": "T6",
    "title": "AI agents move data. Transform?",
    "files": [
     "media/T6/p01.jpg?v=202610010132",
     "media/T6/p02.jpg?v=202610010132",
     "media/T6/p03.jpg?v=202610010132",
     "media/T6/p04.jpg?v=202610010132",
     "media/T6/p05.jpg?v=202610010132",
     "media/T6/p06.jpg?v=202610010132",
     "media/T6/p07.jpg?v=202610010132"
    ]
   },
   "text": "Can AI agents build your data pipelines?\n\nPART OF THEM. The honest benchmarks say which part.\n\nEveryone has seen the demo where an agent builds a pipeline in minutes. Public benchmarks give a more useful picture.\n\nOn ELT-Bench-Verified, published this March, the best agent got extract and load right 96% of the time.\n\nTransformation, the step where business logic lives, came in at 32.51%.\n\n*Moving data is nearly solved. Meaning isn't.*\n\n📦 Extract and load: use agents now. It's repetitive, checkable, and where engineers lose the most hours.\n\n🧠 Transformation: what counts as revenue, which customer is active, how two systems reconcile. Agents get it right about one time in three.\n\n🧪 dbt project tasks: the best score on the Spider 2.0-DBT leaderboard is 65.6%. Better, still not autopilot.\n\n🙋 Trust: only 33% of developers say they trust AI accuracy (Stack Overflow 2025). Healthy scepticism is the right instinct.\n\nSo split the work. AI for the repetitive, checkable steps. Fixed rules wherever results must be predictable. People own the business logic and review what ships.\n\nWhich part of your pipeline would you trust an agent with today?\n\n#DataEngineering #AI #AIAgents",
   "first_comment": "",
   "sources": [
    "ELT-Bench-Verified, arXiv 2603.29399 (Mar 2026): EL 96%, transformation 32.51% (Claude Sonnet 4.5 + SWE-agent); original baseline 37% / 1%",
    "Spider 2.0-DBT leaderboard (read 30 Sep 2026): best 65.6%",
    "Stack Overflow Developer Survey 2025: 33% trust AI accuracy"
   ],
   "numbers_for_signoff": [
    "96%",
    "32.51%",
    "65.6%",
    "33%"
   ]
  },
  {
   "id": "T1",
   "profile": "terry",
   "status": "ready",
   "date": "2026-10-05",
   "time": "10:00",
   "short": "Cost per job is missing jobs",
   "idea": "W2: your cost per job report is missing the jobs that cost the most",
   "format": "Carousel · 8 slides, dark numbered tips",
   "sample": {
    "id": "AB33",
    "creator": "Austin Belcak",
    "what": "Dark numbered carousel: identity cover with highlighted keywords, one tip per slide, white handwritten checklist box",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7477407036645994497"
   },
   "copy_basis": "Sample AB33's own copy structure (headline promise, context, numbered fixes each with a mini checklist, 'you can do this today').",
   "cta": true,
   "media": {
    "type": "carousel",
    "src": "T1",
    "title": "Your cost per job report is missing the jobs that cost the most",
    "files": [
     "media/T1/p01.jpg?v=202610010132",
     "media/T1/p02.jpg?v=202610010132",
     "media/T1/p03.jpg?v=202610010132",
     "media/T1/p04.jpg?v=202610010132",
     "media/T1/p05.jpg?v=202610010132",
     "media/T1/p06.jpg?v=202610010132",
     "media/T1/p07.jpg?v=202610010132",
     "media/T1/p08.jpg?v=202610010132"
    ]
   },
   "text": "Your Databricks cost per job report is probably missing the jobs that cost the most.\n\nHere's why, straight from Databricks' own documentation.\n\nCost gets tied to a job through the job ID in the billing data. Jobs that run on All-Purpose clusters don't carry one. So Databricks' own cost-per-job queries leave them out.\n\nAnd All-Purpose is the most expensive way to run a scheduled job. On AWS Premium, it lists at $0.55 per DBU against $0.15 for job compute. That's 3.67x for the same work.\n\n5 steps to find and fix them:\n\n1. Spot the gap: check how much billed usage has no job ID\n2. Price the gap: compare the All-Purpose rate with job compute\n3. Find the jobs: flag tasks set to run on an existing all-purpose cluster\n4. Move them: point scheduled work at job compute or serverless jobs\n5. Report the rest honestly: untraced spend is a visibility gap, never a saving\n\nStep 4 is configuration, not a migration. It's often the easiest win on the whole bill.\n\nSwipe through for the details.\n\n#Databricks #FinOps #DataEngineering",
   "first_comment": "If you'd like to see this done on a real Databricks bill, BigHammer.ai founder and CEO Srinath Reddy is running a free live masterclass on it: Thursday 15 October, 12:00 PM ET / 5 PM UK, 45 minutes including Q&A. Save a seat here: https://webinar.bighammerai.com/",
   "sources": [
    "Databricks billing + jobs-cost docs: job_id not populated for jobs on all-purpose compute; excluded from cost-per-job queries",
    "Databricks pricing pages (AWS, Premium, US East, Sep 2026): All-Purpose Classic $0.55, Jobs Classic $0.15"
   ],
   "numbers_for_signoff": [
    "$0.55",
    "$0.15",
    "3.67x"
   ]
  },
  {
   "id": "T2",
   "profile": "terry",
   "status": "ready",
   "date": "2026-10-06",
   "time": "10:00",
   "short": "15% busy, 100% billed",
   "idea": "W5: a cluster running at 15% CPU costs the same as one running at 90%",
   "format": "Single image · data graphic as hero, three legs",
   "sample": {
    "id": "AV11",
    "creator": "Alex Vacca (ColdIQ)",
    "what": "Hero data bar split into segments, then three colour-coded columns each with a label, rule, list and example box, closing two-line thesis",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7475485702441336832"
   },
   "copy_basis": "Sample AV11's own copy structure (surprising cost story, the rule, what you own vs what the tool does, closing thesis) adapted to utilisation.",
   "cta": true,
   "media": {
    "type": "image",
    "src": "T2",
    "tall": false,
    "files": [
     "media/T2/image.jpg?v=202610010132"
    ]
   },
   "text": "A Databricks cluster running at 15% CPU costs exactly the same as one running at 90%.\n\nClassic compute is billed on nodes and hours. Not on how busy those nodes are.\n\nSomebody sized a cluster for a peak months ago. The peak passed. The size didn't. It still runs that way every night.\n\nThe good news: Databricks already records what every node was doing, minute by minute, in system.compute.node_timeline.\n\nThe catch: it only keeps that data for 90 days.\n\nLook at two numbers per cluster, the average CPU and the 95th percentile, and you'll find three kinds:\n\n→ Oversized. Average under 20% and still under 40% at its peak. It needs fewer or smaller nodes.\n\n→ Spiky. Quiet most of the run, briefly flat out. It needs a real autoscaling range, not a smaller size.\n\n→ Busy. Working most of the time. Leave it alone and spend your effort elsewhere.\n\nAn average on its own can mislead you. A cluster that averages 18% because it hit 95% for four minutes needs a different fix from one that never goes above 30%.\n\nCheck your top 10 clusters by cost this week, before that data expires.\n\n#Databricks #CloudCost #FinOps",
   "first_comment": "This utilisation check is one of the steps in a free live masterclass by BigHammer.ai founder and CEO Srinath Reddy on reducing Databricks costs: Thursday 15 October, 12:00 PM ET / 5 PM UK. Bring your own cluster questions. Save a seat: https://webinar.bighammerai.com/",
   "sources": [
    "Databricks compute system tables docs: node_timeline minute-level utilisation, 90-day retention",
    "BigHammer email series Issue 6 (avg under 20%, p95 under 40%, 30+ minute runs)"
   ],
   "numbers_for_signoff": [
    "20% / 40% thresholds",
    "90 days"
   ]
  },
  {
   "id": "T3",
   "profile": "terry",
   "status": "ready",
   "date": "2026-10-07",
   "time": "10:00",
   "short": "Poll: which cost question",
   "idea": "W9: which Databricks cost question can nobody in your company answer today?",
   "format": "Native LinkedIn poll (text post)",
   "sample": {
    "id": "PC31",
    "creator": "Patrick James Cumming (Ad Juice)",
    "what": "Text-only event promotion narrative: a contrarian observation, the idea behind the session, then the invitation",
    "url": "https://www.linkedin.com/feed/update/urn:li:activity:7459920320846667777"
   },
   "copy_basis": "Sample PC31's own event-promotion narrative (observation, why it matters, what the session does differently, the invite), turned into a poll so the audience shapes the session.",
   "cta": true,
   "media": {
    "type": "poll",
    "question": "Which Databricks cost question can nobody in your company answer today?",
    "options": [
     "Which job drove the rise",
     "What failed runs cost us",
     "Which spend has no owner",
     "What could run elsewhere"
    ]
   },
   "text": "Most Databricks cost reviews I hear about end the same way.\n\nThe bill went up. Everyone has a theory. Nobody has an answer.\n\nMore workloads. Bigger data. A new team. All plausible, none proven. Then the same meeting happens again next quarter.\n\nThe gap is rarely effort. It's that the questions finance actually asks don't map to anything the platform team can pull up in five minutes.\n\nSo here's a quick poll. Which of these can nobody in your company answer right now?\n\nOn Thursday 15 October, BigHammer.ai founder and CEO Srinath Reddy is running a free live masterclass on exactly these questions: where the answers sit in your own billing data, and what to do about them.\n\nThe most-voted option gets extra time in the session.\n\nVote below, and the link to save a seat is in the first comment.\n\n#Databricks #FinOps #DataLeadership",
   "first_comment": "Thursday 15 October, 12:00 PM ET / 5 PM UK, free and 45 minutes. Srinath Reddy, founder and CEO of BigHammer.ai, walks through where each of these answers sits in your own Databricks billing data. The best three questions from the audience win a $50 Amazon gift card. Save a seat: https://webinar.bighammerai.com/",
   "sources": [
    "BigHammer email series Issues 1-3 and 7 (the four questions)",
    "Webinar page: date, time, gift cards"
   ],
   "numbers_for_signoff": [
    "$50 gift card"
   ]
  }
 ],
 "webinar_url": "https://webinar.bighammerai.com/",
 "sync_url": "https://script.google.com/macros/s/AKfycbwkUPVvQv_Ye9O1IEu5Lt8ABtDzlAZZjprQUk4AFRMSOU1OiJcDPb4DVSBylaXHJ2UWWA/exec"
};
